# https://davidyeiser.com/tutorial/docker-wordpress-theme-setup
# https://cntnr.io/setting-up-wordpress-with-docker-262571249d50
# https://mherman.org/blog/dockerizing-a-react-app/
# https://stackoverflow.com/questions/36387032/how-to-set-a-path-on-host-for-a-named-volume-in-docker-compose-yml
# https://docs.docker.com/storage/volumes/
version: "3"

services:
  db:
    image: "mysql:5.7"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      # https://github.com/docker-library/mysql/issues/51
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: adonis
      MYSQL_USER: root
      MYSQL_PASSWORD:
    networks:
      - backend

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: DanTokyo12345
    networks:
      - backend

volumes:
  db_data:
networks:
  backend:
  frontend:
